# Generated by Django 4.2.2 on 2023-07-30 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='imgae',
            new_name='image',
        ),
    ]
